FROM node:19.2-alpine3.16
# /app ya viene con app
WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

ARG PORT
ARG JWT_SECRET
ARG JWT_EXP
ARG DB_PORT
ARG DB_HOST
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE
ARG DEFAULT_USER_NAME
ARG DEFAULT_USER_EMAIL
ARG DEFAULT_USER_PASSWORD

ENV PORT=$PORT
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXP=$JWT_EXP
ENV DB_PORT=$DB_PORT
ENV DB_HOST=$DB_HOST
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DATABASE=$DB_DATABASE
ENV DEFAULT_USER_NAME=$DEFAULT_USER_NAME
ENV DEFAULT_USER_EMAIL=$DEFAULT_USER_EMAIL
ENV DEFAULT_USER_PASSWORD=$DEFAULT_USER_PASSWORD

# Imprimir el arg para ver el valor recibido
RUN echo "PORT ::: $PORT";
RUN echo "JWT_SECRET ::: $JWT_SECRET";
RUN echo "JWT_EXP ::: $JWT_EXP";
RUN echo "DB_PORT ::: $DB_PORT";
RUN echo "DB_HOST ::: $DB_HOST";
RUN echo "DB_USERNAME ::: $DB_USERNAME";
RUN echo "DB_PASSWORD ::: $DB_PASSWORD";
RUN echo "DB_DATABASE ::: $DB_DATABASE";
RUN echo "DEFAULT_USER_NAME ::: $DEFAULT_USER_NAME";
RUN echo "DEFAULT_USER_EMAIL ::: $DEFAULT_USER_EMAIL";
RUN echo "DEFAULT_USER_PASSWORD ::: $DEFAULT_USER_PASSWORD";

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
